<!-- Group Parent -->
<div class="wpzinc-option">
	<div class="full">
    	<label for="parent"><?php _e( 'Group Parent', 'page-generator-pro' ); ?></label>
    </div>
    <div class="full">
		<?php
		echo $parent_groups_dropdown;

		if ( $parent_group_id ) {
			?>
			<a href="post.php?post=<?php echo $parent_group_id; ?>&action=edit" target="_blank"><?php _e( 'Edit Parent Group', 'page-generator-pro' ); ?></a>
			<?php
		}
		?>
    </div>

    <p class="description">
    	<?php _e( 'To make generated Page(s) / Post(s) from this Group be children of existing Page / Posts generated by another Group, select the Parent Group here.', 'page-generator-pro' ); ?>
    </p>
</div>

<!-- Parent -->
<div class="wpzinc-option sidebar">
	<div class="full">
    	<label for="parent"><?php _e( 'Parent', 'page-generator-pro' ); ?></label>
    </div>
    <div class="full">
		<?php
	    // For each hierarchical post type, output a Post ID field
		if ( is_array( $hierarchical_post_types ) && count( $hierarchical_post_types ) > 0 ) {
			foreach ( $hierarchical_post_types as $type => $post_type ) {
				?>
				<input type="text" id="parent" name="<?php echo $this->base->plugin->name . '[pageParent][' . $type . ']'; ?>" class="post-type-conditional <?php echo $type; ?> widefat" value="<?php echo ( isset( $this->settings['pageParent'][ $type ] ) ? $this->settings['pageParent'][ $type ] : '' ); ?>" />
				<?php
			}
		}
	    ?>
    </div>

    <p class="description">
    	<?php _e( 'To make generated Page(s) / Post(s) the child of an existing Page / Post, enter the parent Page / Post ID or Name (Slug) here.', 'page-generator-pro' ); ?><br />
    	<a href="<?php echo $this->base->plugin->documentation_url; ?>/generate-content/#fields--attributes" rel="noopener" target="_blank">
    		<?php _e( 'How to find the Parent Page ID', 'page-generator-pro' ); ?>
    	</a>
    </p>
</div>